import {useState} from 'react';import {api} from '../api';import {Card} from '../ui';
export default function Content(){const[topic,setTopic]=useState(''),[tone,setTone]=useState('professional'),[caps,setCaps]=useState<any[]>([]),[ce,setCe]=useState(''),[cl,setCl]=useState(false),
 [prompt,setPrompt]=useState(''),[ratio,setRatio]=useState('1:1'),[ov,setOv]=useState(''),[imgs,setImgs]=useState<string[]>([]),[ie,setIe]=useState(''),[il,setIl]=useState(false),
 [niche,setNiche]=useState(''),[tags,setTags]=useState<any>(null),[he,setHe]=useState(''),[when,setWhen]=useState(''),[note,setNote]=useState('');
 const run=async(f:()=>Promise<void>,setL:(b:boolean)=>void,setE:(s:string)=>void)=>{setL(true);setE('');try{await f()}catch(e:any){setE(e.message+' (add the key in .env to enable)')}setL(false)};
 const sched=async(caption:string)=>{if(!when)return setNote('Pick a date/time first');await api('/schedule',{method:'POST',body:{caption,image:null,scheduledAt:new Date(when).toISOString()}});setNote('Scheduled ✔ see Scheduling tab')};
 return <div className="grid"><Card full t="Caption Generator"><div className="row"><input placeholder="topic" value={topic} onChange={e=>setTopic(e.target.value)}/><select value={tone} onChange={e=>setTone(e.target.value)}><option>funny</option><option>professional</option><option>bold</option></select><button className="btn" disabled={cl} onClick={()=>run(async()=>setCaps((await api('/content/captions',{method:'POST',body:{topic,tone}})).variants),setCl,setCe)}>{cl?'Generating…':'Generate 5 variants'}</button><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/><span className="mu">{note}</span></div>{ce&&<div className="dn">{ce}</div>}
 {caps.map((c,i)=><div key={i} className="card" style={{margin:'6px 0'}}><mark>{c.hook}</mark> {c.body} <i>{c.cta}</i><div className="row"><button className="btn g s" onClick={()=>navigator.clipboard.writeText(`${c.hook}\n${c.body}\n${c.cta}`)}>Copy</button><button className="btn g s" onClick={()=>sched(`${c.hook}\n${c.body}\n${c.cta}`)}>Schedule</button></div></div>)}</Card>
 <Card t="Image Generator (Replicate + code-controlled text overlay)"><div className="row"><input placeholder="prompt" value={prompt} onChange={e=>setPrompt(e.target.value)}/><select value={ratio} onChange={e=>setRatio(e.target.value)}><option>1:1</option><option>4:5</option><option>9:16</option></select><input placeholder="overlay text" value={ov} onChange={e=>setOv(e.target.value)}/><button className="btn" disabled={il} onClick={()=>run(async()=>setImgs((await api('/content/image',{method:'POST',body:{prompt,ratio,overlayText:ov}})).images),setIl,setIe)}>{il?'Generating…':'Generate'}</button></div>{ie&&<div className="dn">{ie}</div>}{imgs.map((s,i)=><img key={i} className="gen" src={s}/>)}</Card>
 <Card t="Hashtag Generator"><div className="row"><input placeholder="niche" value={niche} onChange={e=>setNiche(e.target.value)}/><button className="btn" onClick={()=>run(async()=>setTags(await api('/content/hashtags',{method:'POST',body:{niche}})),()=>{},setHe)}>Generate</button></div>{he&&<div className="dn">{he}</div>}{tags&&Object.entries(tags).map(([g,a]:any)=><div key={g}><b>{g}</b><div>{a.map((t:string)=><span className="pill" key={t}>{t}</span>)}</div></div>)}</Card></div>}
